### ISSUE TITLE
Drag-N-Drop Height Too Small

### ISSUE THREAD

**Issue by cjkoepke** [copyblogger/genesis-simple-share#71]
Original issue (with screenshots) is related here: https://github.com/copyblogger/synthesis-platform/issues/1161

Not sure how testing is done these plugins but here are the parameters after my fix:

**Test Branch**: fix-drag-n-drop

**Test Scenario**:
1. Go to the Genesis Simple Share setup page.
2. Drag the boxes around and make sure they meet the verification parameters below.
3. Make sure that the height style in the spui.css file is deactivated in RM. Assuming this works, that will be removed since an override will no longer be needed. Do this by:
a. Right-clicking on the box in Chrome
b. Selecting Inspect Element
c. Selecting the .postbox element on the left, like so: https://cloudup.com/c-lid9C8JMf
d. Unchecking the ```height: 200px !important``` style on the right: https://cloudup.com/c5rtfDPoElu

**Test Verification**:
- [x] Verify that the Pinterest box has consistent padding beneath the input.
- [x] Verify that all boxes are the same height in each row. Move them around to test different layouts.
- [ ] Verify IE fallback support is working in IE 9 or lower.
- [x] Verify that boxes look like my screenshot below in all browsers:

<img width="1152" alt="screen shot 2016-05-05 at 2 56 29 pm" src="https://cloud.githubusercontent.com/assets/2815568/15056949/98e7cf48-12d1-11e6-8d11-151dd7e2e9ca.png">

**Comment by omiq** [comment]
@katyfb13 not sure who is best to test this?

**Comment by cjkoepke** [comment]
Anyone able to test this yet?

**Comment by katyfb13** [comment]
sorry QA has not gotten to this yet. We have a lot of issues in synthesis-platform to get through so it should be in the que since there is a placeholder issue for this over there.

**Comment by katyfb13** [comment]
> Test Branch: fix-drag-n-drop

I am not seeing this branch in my QA site. And I'm not seeing the fix in place in the develop branch

![screen shot 2016-05-17 at 9 03 32 pm](https://cloud.githubusercontent.com/assets/2847436/15345223/dbfb9a76-1c72-11e6-9225-01bc6a44ab86.png)

where should I be seeing this in cbmdev02?

**Comment by cjkoepke** [comment]
@NicktheGeek or @mattlawck (whoever does branch stuff), is there any reason @katyfb13 wouldn't be able to find my branch for this issue? the branch is: fix-drag-n-drop

**Comment by NicktheGeek** [comment]
@cjkoepke you will need to merge it to the rainmaker-develop branch. Then any branch refresh should sync your changes to dev02 for testing. After do a PR to rainmaker-master so we can get it into RM and then merge to develop and pr to master so we can get it into wp.org

**Comment by cjkoepke** [comment]
@katyfb13 I've merged the branch so now you should be able to refresh your branch and see the changes. @NicktheGeek here is the merge info: https://github.com/copyblogger/genesis-simple-share/pull/73

**Comment by katyfb13** [comment]
> you should be able to refresh your branch and see the changes.

I wish it were that simple ;)

**Comment by NicktheGeek** [comment]
@katyfb13 it was merged into rainmaker-develop so refreshing any branch should import the update. You may have to clear your cache to see the changes though.

**Comment by katyfb13** [comment]
I have tried everything I could think of to make the branch appear in my QA site. I've dumped cache, hard refreshed, switched branches multiple times, waited 5 minutes, refreshed and waited 15 minutes, refreshed and waited 45 minutes, changed browsers and repeated all the typical things. I still do not see a branch called 

> fix-drag-n-drop

Is it possible it has a different name? Otherwise, I need someone to look at my katy-prod.cbmdev02 site to see why it won't update branches please

**Comment by katyfb13** [comment]
sorry, just figured out that Nick was saying that it should now work in any branch.

But I don't think this is what we are going for:

![screenshot-katy-prod cbmdev02 rmkr net 2016-05-19 12-25-57](https://cloud.githubusercontent.com/assets/2847436/15403129/0ca60fee-1dbd-11e6-87b5-33a00310f9ed.png)

**Comment by katyfb13** [comment]
also, I've tried dumping cache, hard refreshes, changing to incognito, etc. and it's not fixing. Might be stubborn cache but will have to try later to see if it clears up.

**Comment by cjkoepke** [comment]
@katyfb13 Give me a second to push an update. I know what might be causing that. Also, @NicktheGeek should I just make the changes on rainmaker-develop then?

**Comment by NicktheGeek** [comment]
> should I just make the changes on rainmaker-develop then?

No, please make the change in your branch then merge to rm-develop to the branch. That way when it is approved the branch can be merged to rm-master and develop and we don't risk putting un tested code into master along the way.

**Comment by cjkoepke** [comment]
@katyfb13 Go ahead and refresh your branch and clear cache. Should all be good now.

**Comment by katyfb13** [comment]
Yes, working now, thanks. Just running through all the parameters 👌

**Comment by katyfb13** [comment]
this looks good to me. I tested in my Mac with Chrome, Firefox and Safari. I used Browserstack to look at Windows with IE 10, Firefox and Chrome. Browserstack does not support below IE 10 so couldn't check the older versions of IE.

Going to call this merge ready.

**Comment by katyfb13** [comment]
This needs to be merged asap if it is going to go into RM 2.5
@cjkoepke @NicktheGeek

**Comment by NicktheGeek** [comment]
@cjkoepke can you do a or from your branch to rainmaker-master

**Comment by cjkoepke** [comment]
Hey @katyfb13 and @NicktheGeek, I just submitted the pull request here: https://github.com/copyblogger/genesis-simple-share/pull/75
